# This is a basic workflow to help you get started with Actions

name: Simple Manual Workflow - Three Env

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
    # branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a script
        run: |
          echo "I am running a job in a DEV environment"
  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: [DEV]
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Run a script
        run: |
          echo "I am running a job in a QA environment"
          
  PROD:
    runs-on: ubuntu-latest
    environment: PROD
    needs: [QA]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a script
        run: |
          echo "I am running a job in a PROD environment"
          
  
